apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatnodejs-deployment
  labels:
    app: chatnodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatnodejs
  template:
    metadata:
      labels:
        app: chatnodejs
    spec:
      containers:
      - name: chatnodejs
        image: local/chatnode
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
          - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /                
            port: 3000             
          initialDelaySeconds: 15  
          periodSeconds: 10        
        readinessProbe:
          httpGet:
            path: /api/v1                
            port: 3001             
          initialDelaySeconds: 15   
          periodSeconds: 10         

      - name: mongo-db
        image: mongo
        imagePullPolicy: Never
        ports:
        - containerPort: 27017