apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatnodejs-deployment
  
  labels:
    app: chatnodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatnodejs
  template:
    metadata:
      labels:
        app: chatnodejs
    spec:
      containers:
      - name: chatnodejs
        image: local/chatnode
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
          - containerPort: 3001
        livenessProbe:
          httpGet:
            path: /                
            port: 3000             
          initialDelaySeconds: 30  
          periodSeconds: 10        
        readinessProbe:
          httpGet:
            path: /api/v1                
            port: 3001             
          initialDelaySeconds: 30   
          periodSeconds: 10         

      - name: mongo-db
        image: mongo:latest
        ports:
        - containerPort: 27017
        args: ["--dbpath","/data/db"]
        envFrom:
          - configMapRef:
              name: db-config
        volumeMounts:
        - name: "mongo-data-dir"
          mountPath: "/data/db"
        - name: "init-database"
          mountPath: "/docker-entrypoint-initdb.d/"
      volumes:
      - name: "mongo-data-dir"
      - name: "init-database"
        configMap:
          name: init-db-configmap