apiVersion: v1
kind: Service
metadata:
  name: chatnodejs-service
spec:
  selector:
    app: chatnodejs
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
  - name: api
    protocol: TCP
    port: 3001
    targetPort: 3001